<#
    setup_broker.ps1

    Configure and run the locally-installed Mosquitto MQTT broker so that a
    remote LAN client (the ESP8266) can connect to it.

    The default Mosquitto config only listens on localhost (127.0.0.1) and
    forbids anonymous clients, so a remote ESP8266 cannot connect out of the
    box. This script writes a minimal config that listens on all interfaces
    and allows anonymous access, opens the firewall, then runs the broker in
    the foreground in verbose mode.

    Mosquitto is expected to be installed via:
        winget install EclipseFoundation.Mosquitto

    No arguments are required.
#>

# No params needed; this script takes no arguments.

$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# Directory this script lives in (tools/). Config is written alongside it.
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ConfPath  = Join-Path $ScriptDir "mosquitto.conf"

# ---------------------------------------------------------------------------
# 1. Locate mosquitto.exe
# ---------------------------------------------------------------------------

$MosquittoExe = $null

# Prefer whatever is on PATH.
$cmd = Get-Command mosquitto -ErrorAction SilentlyContinue
if ($cmd) {
    $MosquittoExe = $cmd.Source
}

# Fall back to the common winget / installer locations.
if (-not $MosquittoExe) {
    $candidates = @(
        "C:\Program Files\mosquitto\mosquitto.exe",
        "C:\Program Files (x86)\mosquitto\mosquitto.exe"
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) {
            $MosquittoExe = $c
            break
        }
    }
}

if (-not $MosquittoExe) {
    Write-Host "ERROR: mosquitto.exe was not found." -ForegroundColor Red
    Write-Host "Install it with:" -ForegroundColor Yellow
    Write-Host "    winget install EclipseFoundation.Mosquitto"
    exit 1
}

Write-Host "Found Mosquitto at: $MosquittoExe" -ForegroundColor Green

# ---------------------------------------------------------------------------
# 2. Write the broker config
# ---------------------------------------------------------------------------

# Listen on 0.0.0.0:1884 (all interfaces) and allow anonymous clients so the
# ESP8266 on the LAN can connect. The default config does neither.
# Port 1884 (not the usual 1883) because the winget-installed Mosquitto Windows
# service already holds 1883, but only on localhost and it can't be reconfigured
# without admin. Our LAN-facing broker runs on 1884 bound to 0.0.0.0.
$ConfContent = @"
# mosquitto.conf - generated by setup_broker.ps1
# Allows remote anonymous MQTT clients (e.g. the ESP8266) on the LAN.
# Do NOT use allow_anonymous on an untrusted/public network.

listener 1884 0.0.0.0
allow_anonymous true
"@

Set-Content -Path $ConfPath -Value $ConfContent -Encoding ascii
Write-Host "Wrote config: $ConfPath" -ForegroundColor Green

# ---------------------------------------------------------------------------
# 3. Firewall rule for inbound TCP 1884
# ---------------------------------------------------------------------------

$RuleName = "Mosquitto 1884"
try {
    $existing = Get-NetFirewallRule -DisplayName $RuleName -ErrorAction SilentlyContinue
    if ($existing) {
        Write-Host "Firewall rule '$RuleName' already exists." -ForegroundColor Green
    }
    else {
        New-NetFirewallRule -DisplayName $RuleName `
            -Direction Inbound `
            -Action Allow `
            -Protocol TCP `
            -LocalPort 1884 | Out-Null
        Write-Host "Added firewall rule '$RuleName' (inbound TCP 1884)." -ForegroundColor Green
    }
}
catch {
    Write-Host "NOTE: could not add/check the firewall rule (admin rights may be required)." -ForegroundColor Yellow
    Write-Host "      You can add it manually from an elevated PowerShell:" -ForegroundColor Yellow
    Write-Host "      New-NetFirewallRule -DisplayName `"$RuleName`" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 1884"
}

# ---------------------------------------------------------------------------
# 4. Show LAN IP(s) for the ESP firmware
# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "This PC's LAN IPv4 address(es) - use one of these in the ESP8266 firmware:" -ForegroundColor Cyan
try {
    $addrs = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
        Where-Object {
            $_.IPAddress -ne "127.0.0.1" -and
            $_.PrefixOrigin -ne "WellKnown"
        }
    foreach ($a in $addrs) {
        Write-Host ("    {0}  (interface: {1})" -f $a.IPAddress, $a.InterfaceAlias)
    }
    # Detect and highlight the actual LAN IP on the 192.168.1.x subnet (the
    # Ethernet interface — expected 192.168.1.100).
    $lan = $addrs | Where-Object { $_.IPAddress -like "192.168.1.*" } |
        Select-Object -First 1 -ExpandProperty IPAddress
    if ($lan) {
        Write-Host ("    -> use MQTT_HOST = {0} in the ESP8266 firmware" -f $lan) -ForegroundColor Green
    }
}
catch {
    Write-Host "    (could not enumerate IPs; expected: 192.168.1.100)"
}
Write-Host "    MQTT broker port: 1884"
Write-Host ""

# ---------------------------------------------------------------------------
# 5. Run the broker (foreground, verbose). This blocks.
# ---------------------------------------------------------------------------

Write-Host "Starting Mosquitto in verbose mode. This will block - press Ctrl+C to stop." -ForegroundColor Cyan
Write-Host "Running command:" -ForegroundColor Cyan
Write-Host "    & `"$MosquittoExe`" -v -c `"$ConfPath`""
Write-Host ""

# Use the call operator (&) so paths containing spaces are handled correctly.
& "$MosquittoExe" -v -c "$ConfPath"
